ALTER TABLE "assessments" ADD COLUMN "due_at" TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE "placement_applications" ADD COLUMN "due_at" TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE "placement_requests" ADD COLUMN "due_at" TIMESTAMP WITH TIME ZONE NULL;