ALTER TABLE approved_premises_applications ADD cas1_cru_management_area_id uuid NULL;
ALTER TABLE approved_premises_applications ADD CONSTRAINT approved_premises_applications_cas1_cru_management_areas_fk FOREIGN KEY (cas1_cru_management_area_id) REFERENCES cas1_cru_management_areas(id);
