package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model

import com.fasterxml.jackson.annotation.JsonValue

@Suppress("ktlint:standard:enum-entry-name-case", "EnumNaming")
enum class ApprovedPremisesUserPermission(@get:JsonValue val value: String) {
  applicationWithdrawOthers("cas1_application_withdraw_others"),
  assessAppealedApplication("cas1_assess_appealed_application"),
  assessApplication("cas1_assess_application"),
  assessPlacementApplication("cas1_assess_placement_application"),
  bookingChangeDates("cas1_booking_change_dates"),
  bookingWithdraw("cas1_booking_withdraw"),
  changeRequestList("cas1_change_request_list"),
  changeRequestView("cas1_change_request_view"),
  keyworkerAssignableAs("cas1_keyworker_assignable_as"),
  experimentalNewAssignKeyworkerFlow("cas1_experimental_new_assign_keyworker_flow"),
  experimentalNewRequestForPlacementFlow("cas1_experimental_new_request_for_placement_flow"),
  nationalOccupancyView("cas1_national_occupancy_view"),
  offlineApplicationView("cas1_offline_application_view"),
  outOfServiceBedCreate("cas1_out_of_service_bed_create"),
  outOfServiceBedCreateBedOnHold("cas1_out_of_service_bed_create_bed_on_hold"),
  outOfServiceBedCancel("cas1_out_of_service_bed_cancel"),
  outOfServiceNoDateLimit("cas1_out_of_service_bed_no_date_limit"),
  placementAppealCreate("cas1_placement_appeal_create"),
  placementAppealAssess("cas1_placement_appeal_assess"),
  placementRequestRecordUnableToMatch("cas1_placement_request_record_unable_to_match"),
  processAnAppeal("cas1_process_an_appeal"),
  transferCreate("cas1_transfer_create"),
  transferAssess("cas1_transfer_assess"),
  userList("cas1_user_list"),
  userSummaryList("cas1_user_summary_list"),
  userManagement("cas1_user_management"),
  viewAssignedAssessments("cas1_view_assigned_assessments"),
  viewCruDashboard("cas1_view_cru_dashboard"),
  viewManageTasks("cas1_view_manage_tasks"),
  viewOutOfServiceBeds("cas1_view_out_of_service_beds"),
  requestForPlacementWithdrawOthers("cas1_request_for_placement_withdraw_others"),
  spaceBookingCreate("cas1_space_booking_create"),
  spaceBookingList("cas1_space_booking_list"),
  spaceBookingRecordArrival("cas1_space_booking_record_arrival"),
  spaceBookingRecordArrivalNoDateLimit("cas1_space_booking_record_arrival_no_date_limit"),
  spaceBookingRecordDeparture("cas1_space_booking_record_departure"),
  spaceBookingRecordDepartureNoDateLimit("cas1_space_booking_record_departure_no_date_limit"),
  spaceBookingRecordNonArrival("cas1_space_booking_record_non_arrival"),
  spaceBookingRecordNonArrivalNoDateLimit("cas1_space_booking_record_non_arrival_no_date_limit"),
  spaceBookingRecordKeyworker("cas1_space_booking_record_keyworker"),
  spaceBookingView("cas1_space_booking_view"),
  spaceBookingWithdraw("cas1_space_booking_withdraw"),
  spaceBookingShorten("cas1_space_booking_shorten"),
  premisesCapacityReportView("cas1_premises_capacity_report_view"),
  tasksList("cas1_tasks_list"),
  taskAllocate("cas1_tasks_allocate"),
  premisesView("cas1_premises_view"),
  premisesManage("cas1_premises_manage"),
  reportsView("cas1_reports_view"),
  reportsViewWithPii("cas1_reports_view_with_pii"),
  premisesLocalRestrictionsManage("cas1_premises_local_restrictions_manage"),
  cas1TestExperimentalPermission("cas1_test_experimental_permission"),
  cas1SpaceBookingCreateAdditional("cas1_space_booking_create_additional"),
}
