/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas1

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1NewOutOfServiceBed
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1NewOutOfServiceBedCancellation
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1OutOfServiceBed
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1OutOfServiceBedCancellation
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1OutOfServiceBedSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Problem
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SortDirection
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Temporality
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.UpdateCas1OutOfServiceBed
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ValidationError
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RestController
interface OutOfServiceBedsCas1 {

    fun getDelegate(): OutOfServiceBedsCas1Delegate = object: OutOfServiceBedsCas1Delegate {}

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Posts a cancellation to a specified out-of-service bed",
        operationId = "cancelOutOfServiceBed",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Cas1OutOfServiceBedCancellation::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "404", description = "invalid premises ID or out-of-service bed ID", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}/cancellations"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun cancelOutOfServiceBed(@Parameter(description = "ID of the premises the cancellation is related to", required = true) @PathVariable("premisesId") premisesId: java.util.UUID,@Parameter(description = "ID of the out-of-service bed", required = true) @PathVariable("outOfServiceBedId") outOfServiceBedId: java.util.UUID,@Parameter(description = "details of the cancellation", required = true) @RequestBody body: Cas1NewOutOfServiceBedCancellation): ResponseEntity<Cas1OutOfServiceBedCancellation> {
        return getDelegate().cancelOutOfServiceBed(premisesId, outOfServiceBedId, body)
    }

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Posts an out-of-service bed to a specified approved premises",
        operationId = "createOutOfServiceBed",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Cas1OutOfServiceBed::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "404", description = "invalid premises ID or booking ID", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/premises/{premisesId}/out-of-service-beds"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun createOutOfServiceBed(@Parameter(description = "ID of the premises the out-of-service bed is related to", required = true) @PathVariable("premisesId") premisesId: java.util.UUID,@Parameter(description = "details of the out-of-service bed", required = true) @RequestBody body: Cas1NewOutOfServiceBed): ResponseEntity<Cas1OutOfServiceBed> {
        return getDelegate().createOutOfServiceBed(premisesId, body)
    }

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Returns a specific out-of-service bed for a premises",
        operationId = "getOutOfServiceBed",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Cas1OutOfServiceBed::class))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "404", description = "invalid premises or out-of-service bed ID", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}"],
            produces = ["application/json"]
    )
    fun getOutOfServiceBed(@Parameter(description = "ID of the premises the out-of-service bed is related to", required = true) @PathVariable("premisesId") premisesId: java.util.UUID,@Parameter(description = "ID of the out-of-service bed", required = true) @PathVariable("outOfServiceBedId") outOfServiceBedId: java.util.UUID): ResponseEntity<Cas1OutOfServiceBed> {
        return getDelegate().getOutOfServiceBed(premisesId, outOfServiceBedId)
    }

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Lists all Out-Of-Service Beds entries",
        operationId = "getOutOfServiceBeds",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = Cas1OutOfServiceBed::class)))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/out-of-service-beds"],
            produces = ["application/json"]
    )
    fun getOutOfServiceBeds(@Parameter(description = "If provided, restrict the results to only those with the given temporality/ies.") @RequestParam(value = "temporality", required = false) temporality: kotlin.collections.List<Temporality>?,@Parameter(description = "If provided, restrict the results to only those in the premises with the given ID.") @RequestParam(value = "premisesId", required = false) premisesId: java.util.UUID?,@Parameter(description = "If provided, restrict the results to only those within the AP area with the given ID.") @RequestParam(value = "apAreaId", required = false) apAreaId: java.util.UUID?,@Parameter(description = "The direction to sort the results by. If blank, will sort in descending order", schema = Schema(allowableValues = ["asc", "desc"])) @RequestParam(value = "sortDirection", required = false) sortDirection: SortDirection?,@Parameter(description = "The field to sort the results by.", schema = Schema(allowableValues = ["premisesName", "roomName", "bedName", "startDate", "endDate", "reason", "daysLost"])) @RequestParam(value = "sortBy", required = false) sortBy: Cas1OutOfServiceBedSortField?,@Parameter(description = "Page number of results to return. If not provided results will not be paged") @RequestParam(value = "page", required = false) page: kotlin.Int?,@Parameter(description = "Number of items to return per page (defaults to 10)") @RequestParam(value = "perPage", required = false) perPage: kotlin.Int?): ResponseEntity<List<Cas1OutOfServiceBed>> {
        return getDelegate().getOutOfServiceBeds(temporality, premisesId, apAreaId, sortDirection, sortBy, page, perPage)
    }

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Lists all Out-Of-Service Beds entries for the Premises",
        operationId = "getOutOfServiceBedsForPremises",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = Cas1OutOfServiceBed::class)))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/premises/{premisesId}/out-of-service-beds"],
            produces = ["application/json"]
    )
    fun getOutOfServiceBedsForPremises(@Parameter(description = "ID of the premises to show out-of-service beds for", required = true) @PathVariable("premisesId") premisesId: java.util.UUID): ResponseEntity<List<Cas1OutOfServiceBed>> {
        return getDelegate().getOutOfServiceBedsForPremises(premisesId)
    }

    @Operation(
        tags = ["out-of-service beds",],
        summary = "Updates an out-of-service bed for a premises",
        operationId = "updateOutOfServiceBed",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Cas1OutOfServiceBed::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "404", description = "invalid premises ID or booking ID", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.PUT],
            value = ["/premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun updateOutOfServiceBed(@Parameter(description = "ID of the premises the out-of-service bed is related to", required = true) @PathVariable("premisesId") premisesId: java.util.UUID,@Parameter(description = "ID of the out-of-service bed", required = true) @PathVariable("outOfServiceBedId") outOfServiceBedId: java.util.UUID,@Parameter(description = "details of the out-of-service bed", required = true) @RequestBody body: UpdateCas1OutOfServiceBed): ResponseEntity<Cas1OutOfServiceBed> {
        return getDelegate().updateOutOfServiceBed(premisesId, outOfServiceBedId, body)
    }
}
