package uk.gov.justice.digital.hmpps.approvedpremisesapi.cas2.model

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ServiceName
import java.util.UUID

enum class Cas2AssessmentStatusDetail(
  val id: UUID,
  val lowerCaseName: String,
  val label: String,
  val applicableToServices: List<ServiceName>,
  val parentStatus: Cas2AssessmentStatus,
) {
  // Found in MORE_INFO_REQUESTED Status
  PERSONAL_INFORMATION(
    id = UUID.fromString("fabbb8c0-344e-4a9d-a964-7987b22d09c6"),
    lowerCaseName = "personalInformation",
    label = "Personal information",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  APPLICANT_DETAILS(
    id = UUID.fromString("3df29b1b-e2fc-4df7-b4b8-0527cd9e3a6f"),
    lowerCaseName = "applicantDetails",
    label = "Applicant details",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  CONCERNS_TO_OTHERS(
    id = UUID.fromString("28926b7b-2056-478c-95fe-a611967b8fab"),
    lowerCaseName = "concernsToOthers",
    label = "Concerns to others",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  CONCERNS_TO_THE_APPLICANT(
    id = UUID.fromString("76be117e-c496-489c-a69d-ef26a05a6f64"),
    lowerCaseName = "concernsToTheApplicant",
    label = "Concerns to the applicant",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  CURRENT_ALLEGED_OFFENCES(
    id = UUID.fromString("03718bee-a0f1-4a5d-b095-e23c2b1211ab"),
    lowerCaseName = "currentAllegedOffences",
    label = "Current alleged offences",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  PREVIOUS_UNSPENT_CONVICTIONS(
    id = UUID.fromString("53f17f5b-c3bb-4bd2-9ccb-b5f0664aa104"),
    lowerCaseName = "previousUnspentConvictions",
    label = "Previous unspent convictions",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  PROBATION_AND_OASYS(
    id = UUID.fromString("4c8e39ea-0f8b-4131-a781-cac706f38914"),
    lowerCaseName = "probationAndOASys",
    label = "Probation & OASys",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  FUNDING_AND_ID(
    id = UUID.fromString("0e78cbc4-4139-4402-8a8a-763d9ca5d93b"),
    lowerCaseName = "fundingAndID",
    label = "Funding & ID",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  EXCLUSION_ZONES_AND_AREAS(
    id = UUID.fromString("05669c8a-d65c-48d2-a5e4-0c3f6fc8977b"),
    lowerCaseName = "exclusionZonesAndAreas",
    label = "Exclusion zones and preferred areas",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  HEALTH_NEEDS(
    id = UUID.fromString("831c241d-63f3-4d17-b969-b8154d7e4902"),
    lowerCaseName = "healthNeeds",
    label = "Health needs",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  RISK_TO_SELF(
    id = UUID.fromString("7ba5cd7d-8ae3-4fe5-bb27-9367197ea160"),
    lowerCaseName = "riskToSelf",
    label = "Risk to self",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  RISK_OF_SERIOUS_HARM(
    id = UUID.fromString("8641d719-7356-42d3-8363-e323bf76caec"),
    lowerCaseName = "riskOfSeriousHarm",
    label = "Risk of serious harm",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  CURRENT_OFFENCES(
    id = UUID.fromString("90f075ae-0b9f-445b-a9b5-1095abca87dc"),
    lowerCaseName = "currentOffences",
    label = "Current offences",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  OFFENDING_HISTORY(
    id = UUID.fromString("8ce77ea1-324e-4ac8-be8c-33d6d4d927f8"),
    lowerCaseName = "offendingHistory",
    label = "Offending history",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  HDC_AND_CPP(
    id = UUID.fromString("d2c44705-2795-4610-9879-dcf26940e121"),
    lowerCaseName = "hdcAndCpp",
    label = "HDC licence and CPP details",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),
  OTHER_MORE_INFO_REQUESTED(
    id = UUID.fromString("94631a70-6c51-43d6-9112-2b6d042b5aa0"),
    lowerCaseName = "other",
    label = "Other",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.MORE_INFO_REQUESTED,
  ),

  // Found in OFFER_DECLINED Status
  AREA_UNSUITABLE(
    id = UUID.fromString("62645779-242d-4601-a8f8-d2cbf1d41dfa"),
    lowerCaseName = "areaUnsuitable",
    label = "Area unsuitable",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  CHANGE_OF_CIRCUMSTANCES_OFFER_DECLINED(
    id = UUID.fromString("fc38f750-e9d2-4270-b542-d38286b9855c"),
    lowerCaseName = "changeOfCircumstances",
    label = "Change of circumstances",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  NO_RESPONSE(
    id = UUID.fromString("31122b89-e087-4b5f-b59a-f7ffa0dd3e0c"),
    lowerCaseName = "noResponse",
    label = "No response",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  OFFER_WITHDRAWN_BY_NACRO(
    id = UUID.fromString("32e62af3-6ea5-4496-a82c-b7bad67080a5"),
    lowerCaseName = "offerWithdrawnByNacro",
    label = "Offer withdrawn by Nacro",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  PROPERTY_UNSUITABLE(
    id = UUID.fromString("b5bfbff4-aaa6-4fb0-ba36-5bca58927dc5"),
    lowerCaseName = "propertyUnsuitable",
    label = "Property unsuitable for needs",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  WITHDRAWN_BY_REFERRER(
    id = UUID.fromString("f58267b8-f91b-4a4f-9aa2-80089ba111e4"),
    lowerCaseName = "withdrawnByReferrer",
    label = "Withdrawn by referrer",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  REHOUSED_BY_ANOTHER_LANDLORD(
    id = UUID.fromString("ed5d529c-d7d1-4f29-a0c0-89fd104cc320"),
    lowerCaseName = "rehousedByAnotherLandlord",
    label = "Rehoused by another landlord",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  APPLICANT_BAILED_TO_NON_CAS2_ACCOMMODATION_OFFER_DECLINED(
    id = UUID.fromString("37aa6cab-1ef7-497e-8a8c-624c9ab69f5a"),
    lowerCaseName = "applicantBailedToNonCAS2Accommodation",
    label = "Applicant bailed to non CAS2 accommodation",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  APPLICANT_REMANDED_IN_CUSTODY_OFFER_DECLINED(
    id = UUID.fromString("566f7a9e-00c4-431d-9b3c-af87ff78379d"),
    lowerCaseName = "applicantRemandedInCustody",
    label = "Applicant remanded in custody",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),
  APPLICANT_UNABLE_TO_AFFORD_RENT(
    id = UUID.fromString("74397513-72f8-4efc-9ecf-32adf8c1db8a"),
    lowerCaseName = "applicantUnableToAffordRent",
    label = "Applicant unable to afford rent",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.OFFER_DECLINED,
  ),

  // Found in WITHDRAWN Status
  HDC_NO_LONGER_ELIGIBLE(
    id = UUID.fromString("e4a2391e-e847-427a-a913-51e0b0ad9f52"),
    lowerCaseName = "hdcNoLongerEligible",
    label = "HDC - no longer eligible",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  GOVERNOR_DECIDED_UNSUITABLE(
    id = UUID.fromString("c5dce0d2-fc05-4a07-8157-25b8821cdb06"),
    lowerCaseName = "governorDecidedUnsuitable",
    label = "Governor - decided unsuitable",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  GOVERNOR_CHOSEN_ALTERNATIVE(
    id = UUID.fromString("3fb37f85-be88-4eee-812d-af122e268eef"),
    lowerCaseName = "governorChosenAlternative",
    label = "Governor - chosen alternative accommodation",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  GOVERNOR_OTHER(
    id = UUID.fromString("8a857a7d-94f9-43ec-963c-2a2528e88a6e"),
    lowerCaseName = "governorOther",
    label = "Governor - other",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  WITHDREW_OR_DECLINED_OFFER(
    id = UUID.fromString("d3c789b8-947d-4e24-9cef-335545d85abe"),
    lowerCaseName = "withdrewOrDeclinedOffer",
    label = "Withdrew or declined offer",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  PERSON_TRANSFERRED_TO_ANOTHER_PRISON_WITHDRAWAL(
    id = UUID.fromString("6fc8d3b7-eb53-479d-8903-3880a9ed563f"),
    lowerCaseName = "personTransferredToAnotherPrisonWithdrawal",
    label = "Person transferred to another prison",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  CHANGE_OF_CIRCUMSTANCES_WITHDRAWN(
    id = UUID.fromString("3acf6010-820a-458d-ae8d-1d8a937af890"),
    lowerCaseName = "changeOfCircumstances",
    label = "Change of circumstances",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  SENTENCING_HEARING_BOOKED(
    id = UUID.fromString("cc5e63f7-c37a-46f5-a83a-5953e40881c6"),
    lowerCaseName = "sentencingHearingBooked",
    label = "Sentencing hearing booked",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  APPLICANT_TRANSFERRED_TO_ANOTHER_PRISON_WITHDRAWAL(
    id = UUID.fromString("766a1675-b917-4532-8485-6ec0380f4f4c"),
    lowerCaseName = "applicantTransferredToAnotherPrisonWithdrawal",
    label = "Applicant transferred to another prison",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  APPLICANT_BAILED_TO_NON_CAS2_ACCOMMODATION_WITHDRAWN(
    id = UUID.fromString("c985337e-b9a7-4609-ac9b-fb8b5ec4a48a"),
    lowerCaseName = "applicantBailedToNonCAS2Accommodation",
    label = "Applicant bailed to non CAS2 accommodation",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  APPLICANT_GIVEN_COMMUNITY_SENTENCE(
    id = UUID.fromString("170787fa-8474-40e7-bdf7-c9f072ce06ef"),
    lowerCaseName = "applicantGivenCommunitySentence",
    label = "Applicant given community sentence",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  APPLICANT_GIVEN_CUSTODIAL_SENTENCE(
    id = UUID.fromString("fec969b5-6cab-459e-a595-8337e43b34a8"),
    lowerCaseName = "applicantGivenCustodialSentence",
    label = "Applicant given custodial sentence",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  OTHER_SENTENCE(
    id = UUID.fromString("3440c6c1-b5ff-4b76-ae48-ecf80a3cec49"),
    lowerCaseName = "otherSentence",
    label = "Other sentence",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),
  APPLICANT_REMANDED_IN_CUSTODY_WITHDRAWN(
    id = UUID.fromString("cf339ef6-bcd7-47ae-8f54-b0011a46a3c8"),
    lowerCaseName = "applicantRemandedInCustody",
    label = "Applicant remanded in custody",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.WITHDRAWN,
  ),

  // Found in CANCELLED Status
  NACRO_ASSESSED_AS_HIGH_RISK(
    id = UUID.fromString("ba46bbe0-8fb6-4539-cccc-5586e6bfe8b6"),
    lowerCaseName = "nacroAssessedAsHighRisk",
    label = "NACRO assessed as high risk",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  ASSESSED_AS_HIGH_RISK(
    id = UUID.fromString("ba46bbe0-8fb6-4539-895d-5586e6bfe8b6"),
    lowerCaseName = "assessedAsHighRisk",
    label = "Assessed as high risk",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NOT_ELIGIBLE(
    id = UUID.fromString("522bb736-aeb6-480f-a51a-2bf3dcfcd482"),
    lowerCaseName = "notEligible",
    label = "Not eligible",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NO_RECOURSE_TO_PUBLIC_FUNDS(
    id = UUID.fromString("ccf43af1-359b-4a14-8941-85eefa88f016"),
    lowerCaseName = "noRecourseToPublicFunds",
    label = "No recourse to public funds",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NO_PROPERTY_AVAILABLE(
    id = UUID.fromString("c149a14d-ba06-420a-b844-5edfc02da6b1"),
    lowerCaseName = "noPropertyAvailable",
    label = "No property available",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NO_FEMALE_PROPERTY_AVAILABLE(
    id = UUID.fromString("3fbdccc9-4858-4ae4-abb5-bd2b90d96d96"),
    lowerCaseName = "noFemalePropertyAvailable",
    label = "No female property available",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NO_ADAPTED_PROPERTY_AVAILABLE(
    id = UUID.fromString("bc539d6d-c353-49fa-847f-6967a148c527"),
    lowerCaseName = "noAdaptedPropertyAvailable",
    label = "No adapted property available",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  NO_SUITABLE_PROPERTY_AVAILABLE(
    id = UUID.fromString("78636840-0155-45d4-971e-fe8d2d6c660c"),
    lowerCaseName = "noSuitablePropertyAvailable",
    label = "No suitable property available",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  INCOMPLETE_REFERRAL(
    id = UUID.fromString("7e8749c9-5254-4dae-90ed-590cf9f59847"),
    lowerCaseName = "incompleteReferral",
    label = "Incomplete referral",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  CREATED_IN_ERROR(
    id = UUID.fromString("d1d96185-d92a-450b-b47f-bcce50356eed"),
    lowerCaseName = "createdInError",
    label = "Created in error",
    applicableToServices = listOf(ServiceName.cas2, ServiceName.cas2v2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  HDC_NOT_ELIGIBLE(
    id = UUID.fromString("f38f55c0-fda6-44f8-a3b1-a7c0a990bc51"),
    lowerCaseName = "hdcNotEligible",
    label = "HDC not eligible",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
  PERSON_TRANSFERRED_TO_ANOTHER_PRISON(
    id = UUID.fromString("4f1033ab-2dea-47ce-8a86-7c47b3ccadd8"),
    lowerCaseName = "personTransferredToAnotherPrison",
    label = "Person transferred to another prison",
    applicableToServices = listOf(ServiceName.cas2),
    parentStatus = Cas2AssessmentStatus.CANCELLED,
  ),
}
