package uk.gov.justice.digital.hmpps.approvedpremisesapi.cas2.controller

import io.swagger.v3.oas.annotations.Operation
import org.slf4j.LoggerFactory
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.OASysSections
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.OASysSupportingInformationQuestion

@RestController
@RequestMapping(path = ["/cas2"])
class Cas2DummyController {
  private val log = LoggerFactory.getLogger(this::class.java)

  @Operation(
    description = "This is a temporary dummy endpoint that adds models missing from autogenerated swagger documentation that are expected by the UI. " +
      "This will be removed once the UI has refactored the code to use approriate types - https://dsdmoj.atlassian.net/browse/CAS-1845.",
  )
  @GetMapping(path = ["/dummy"])
  fun test(
    @RequestBody(required = true) request: ClassesToInclude,
  ) {
    // for linting reasons
    log.info("Generating", request.javaClass.classes)
  }
}

data class ClassesToInclude(
  val oaSysSections: OASysSections,
  val oaSysSupportingInformationQuestion: OASysSupportingInformationQuestion,
)
