openapi: 3.0.1
info:
  version: 1.0.1
  title: 'Transitional Accommodation Services (CAS3)'
servers:
  - url: /cas3
paths:
  /applications:
    get:
      tags:
        - Operations on all applications
      summary: Lists all applications that the user has created
      operationId: getApplicationsForUser
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/Cas3ApplicationSummary'

    post:
      tags:
        - Operations on applications
      summary: Creates an application
      operationId: postApplication
      parameters:
        - name: createWithRisks
          in: query
          required: false
          description: Instructs the API to create and return risk information from the OASys API (defaults to true)
          schema:
            type: boolean
      requestBody:
        description: Information to create a blank application with
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3NewApplication'
        required: true
      responses:
        201:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Application'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        404:
          description: invalid CRN
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
      x-codegen-request-body-name: body
  /applications/{applicationId}:
    get:
      tags:
        - Operations on applications
      summary: Gets a single application by its ID
      operationId: getApplicationById
      parameters:
        - name: applicationId
          in: path
          description: ID of the application
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Application'

    put:
      tags:
        - Operations on applications
      summary: Updates an application
      operationId: putApplication
      parameters:
        - name: applicationId
          in: path
          description: ID of the application
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Information to update the application with
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3UpdateApplication'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Application'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'

      x-codegen-request-body-name: body
    delete:
      operationId: deleteApplication
      tags:
        - Operations on application
      summary: Soft delete a draft application
      parameters:
        - name: applicationId
          in: path
          description: Id of the application
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
  /applications/{applicationId}/submission:
    post:
      tags:
        - Application data
      summary: Submits an Application
      operationId: postApplicationSubmission
      parameters:
        - in: path
          name: applicationId
          required: true
          description: Id of the application
          schema:
            type: string
            format: uuid
      requestBody:
        description: Information needed to submit an application
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3SubmitApplication'
        required: true
      responses:
        200:
          description: successfully submitted the application
        400:
          description: application has already been submitted
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'

  /reports/{reportName}:
    get:
      tags:
        - CAS3 Reports
      summary: Returns a spreadsheet of all data metrics for the 'reportName'.
      operationId: reportsReportNameGet
      parameters:
        - name: reportName
          in: path
          description: Name of the report to download
          required: true
          schema:
            $ref: 'cas3-schemas.yml#/components/schemas/Cas3ReportType'
        - name: probationRegionId
          in: query
          required: false
          description: If provided, only this region will be returned
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          required: true
          description: Start of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: End of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
      responses:
        200:
          description: Successfully retrieved the report
          content:
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
              schema:
                type: string
                format: binary
  /timeline/{assessmentId}:
    get:
      operationId: getTimelineEntries
      tags:
        - CAS3
      summary: Returns the timeline entries for a given Assessment.
      parameters:
        - name: assessmentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfully retrieved the timeline events
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '_shared.yml#/components/schemas/ReferralHistoryNote'
  /premises/summary:
    get:
      tags:
        - Premises
      summary: Returns a list of premises
      operationId: getPremisesSummary
      parameters:
        - name: postcodeOrAddress
          in: query
          description: postcode Or address to filter premises
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/Cas3PremisesSummary'
  /premises/search:
    get:
      tags:
        - Premises
      summary: Searches for premises with the given parameters
      operationId: searchPremises
      parameters:
        - name: postcodeOrAddress
          in: query
          description: postcode Or address to filter premises
          schema:
            type: string
        - name: premisesStatus
          in: query
          description: premises status to filter premises
          schema:
            $ref: 'cas3-schemas.yml#/components/schemas/Cas3PremisesStatus'
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                  $ref: 'cas3-schemas.yml#/components/schemas/Cas3PremisesSearchResults'
  /premises/{premisesId}/bookings/{bookingId}/departures:
    post:
      tags:
        - Operations on bookings
      summary: Posts a departure to a specified booking
      operationId: postPremisesBookingDeparture
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the booking is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: bookingId
          in: path
          description: ID of the booking
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the departure
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3NewDeparture'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Departure'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
      x-codegen-request-body-name: body
  /premises/{premisesId}/future-bookings:
    get:
      tags:
        - Operations on premises
      summary: Returns all future bookings for a premises for a given statuses
      operationId: getPremisesFutureBookings
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises to get bookings for
          required: true
          schema:
            type: string
            format: uuid
        - name: statuses
          in: query
          description: Only return bookings with these statuses
          required: true
          schema:
            type: array
            items:
              $ref: '_shared.yml#/components/schemas/BookingStatus'
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/FutureBooking'
  /premises/{premisesId}/bedspaces:
    get:
      tags:
        - Bedspaces
      summary: Lists all bedspaces for the given premises
      operationId: getPremisesBedspaces
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises to list the bedspaces for
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/Cas3Bedspace'
    post:
      tags:
        - Bedspaces
      summary: Adds a new bedspace for a premises
      operationId: createBedspace
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the bedspace is in
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the new bedspace
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3NewBedspace'
        required: true
      responses:
        201:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Bedspace'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        404:
          description: invalid premises ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
      x-codegen-request-body-name: body
  /premises/{premisesId}/bedspaces/{bedspaceId}:
    get:
      summary: Returns a specific bedspace for a premises
      operationId: getPremisesBedspace
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the bedspace is in
          required: true
          schema:
            type: string
            format: uuid
        - name: bedspaceId
          in: path
          description: ID of the bedspace to get
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Bedspace'
        404:
          description: invalid premises ID or bedspace ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
  /bedspaces/search:
    post:
      summary: Searches for available Beds within the given parameters
      operationId: postBedspaceSearch
      requestBody:
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3BedspaceSearchParameters'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3BedspaceSearchResults'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
  /people/{crn}/oasys/riskManagement:
    get:
      tags:
        - OAsys
      operationId: riskManagement
      parameters:
        - name: crn
          in: path
          description: CRN of the Person to fetch latest OASys selection
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3OASysGroup'
        404:
          description: invalid CRN
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
