openapi: 3.0.1
info:
  version: 1.0.1
  title: 'Transitional Accommodation Services (CAS3)'
servers:
  - url: /cas3
paths:
  /reports/{reportName}:
    get:
      tags:
        - CAS3 Reports
      summary: Returns a spreadsheet of all data metrics for the 'reportName'.
      operationId: reportsReportNameGet
      parameters:
        - name: reportName
          in: path
          description: Name of the report to download
          required: true
          schema:
            $ref: 'cas3-schemas.yml#/components/schemas/Cas3ReportType'
        - name: probationRegionId
          in: query
          required: false
          description: If provided, only this region will be returned
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          required: true
          description: Start of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: End of date range to return
          example: '2024-02-21'
          schema:
            type: string
            format: date
      responses:
        200:
          description: Successfully retrieved the report
          content:
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
              schema:
                type: string
                format: binary
  /timeline/{assessmentId}:
    get:
      operationId: getTimelineEntries
      tags:
        - CAS3
      summary: Returns the timeline entries for a given Assessment.
      parameters:
        - name: assessmentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successfully retrieved the timeline events
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '_shared.yml#/components/schemas/ReferralHistoryNote'
  /applications/{applicationId}:
    delete:
      operationId: deleteApplication
      tags:
        - Operations on application
      summary: Soft delete a draft application
      parameters:
        - name: applicationId
          in: path
          description: Id of the application
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
  /premises/summary:
    get:
      tags:
        - Premises
      summary: Returns a list of premises
      operationId: getPremisesSummary
      parameters:
        - name: postcodeOrAddress
          in: query
          description: postcode Or address to filter premises
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/Cas3PremisesSummary'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
  /premises/{premisesId}/bookings/{bookingId}/departures:
    post:
      tags:
        - Operations on bookings
      summary: Posts a departure to a specified booking
      operationId: postPremisesBookingDeparture
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the booking is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: bookingId
          in: path
          description: ID of the booking
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the departure
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3NewDeparture'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3Departure'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
  /premises/{premisesId}/future-bookings:
    get:
      tags:
        - Operations on premises
      summary: Returns all future bookings for a premises for a given statuses
      operationId: getPremisesFutureBookings
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises to get bookings for
          required: true
          schema:
            type: string
            format: uuid
        - name: statuses
          in: query
          description: Only return bookings with these statuses
          required: true
          schema:
            type: array
            items:
              $ref: '_shared.yml#/components/schemas/BookingStatus'
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'cas3-schemas.yml#/components/schemas/FutureBooking'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
  /bedspaces/search:
    post:
      summary: Searches for available Beds within the given parameters
      operationId: postBedspaceSearch
      requestBody:
        content:
          'application/json':
            schema:
              $ref: 'cas3-schemas.yml#/components/schemas/Cas3BedspaceSearchParameters'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: 'cas3-schemas.yml#/components/schemas/Cas3BedspaceSearchResults'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
