/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas2

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas2ReportName

interface ReportsCas2 {

  fun getDelegate(): ReportsCas2Delegate = object : ReportsCas2Delegate {}

  @Operation(
    tags = ["Reports"],
    summary = "Returns a 'report' spreadsheet of metrics",
    operationId = "reportsReportNameGet",
    description = """""",
    responses = [
      ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = org.springframework.core.io.Resource::class))]),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.GET],
    value = ["/reports/{reportName}"],
    produces = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
  )
  fun reportsReportNameGet(@Parameter(description = "name of the report to download", required = true, schema = Schema(allowableValues = ["\"submitted-applications\"", "\"application-status-updates\"", "\"unsubmitted-applications\""])) @PathVariable("reportName") reportName: Cas2ReportName): ResponseEntity<org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody> {
    return getDelegate().reportsReportNameGet(reportName)
  }
}
