package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate

data class ApplicationReportRow(
  val id: String,
  val crn: String,
  val tier: String?,
  val lastAllocatedToAssessorDate: LocalDate?,
  val applicationAssessedDate: LocalDate?,
  val assessorCru: String?,
  val assessmentDecision: String?,
  val assessmentDecisionRationale: String?,
  val applicantReasonForLateApplication: String?,
  val applicantReasonForLateApplicationDetail: String?,
  val assessorAgreeWithShortNoticeReason: String?,
  val assessorReasonForLateApplication: String?,
  val assessorReasonForLateApplicationDetail: String?,
  val ageInYears: Int?,
  val gender: String?,
  val mappa: String,
  val offenceId: String?,
  val noms: String?,
  val premisesType: String?,
  val releaseType: String?,
  val sentenceType: String?,
  val applicationSubmissionDate: LocalDate?,
  val referralLdu: String?,
  val referralRegion: String?,
  val referralTeam: String?,
  val referrerUsername: String?,
  val targetLocation: String?,
  val applicationWithdrawalDate: LocalDate?,
  val applicationWithdrawalReason: String?,
  val expectedArrivalDate: LocalDate?,
  val expectedDepartureDate: LocalDate?,
  val assessmentAppealCount: Int?,
  val lastAssessmentAppealedDecision: String?,
  val lastAssessmentAppealedDate: LocalDate?,
  val assessmentAppealedFromStatus: String?,
)
