package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate
import java.time.LocalDateTime

data class ApplicationReportRow(
  val id: String,
  val crn: String,
  val lastAllocatedToAssessorDate: LocalDate?,
  val applicationAssessedDate: LocalDate?,
  val assessorCru: String?,
  val assessmentDecision: String?,
  val assessmentDecisionRationale: String?,
  val agreeWithShortNoticeReason: String?,
  val reasonForLateApplication: String?,
  val ageInYears: Int?,
  val gender: String?,
  val mappa: String,
  val offenceId: String?,
  val noms: String?,
  val premisesType: String?,
  val releaseType: String?,
  val sentenceType: String?,
  val applicationSubmissionDate: LocalDate?,
  val referralLdu: String?,
  val referralRegion: String?,
  val referralTeam: String?,
  val referrerUsername: String?,
  val targetLocation: String?,
  val applicationWithdrawalDate: LocalDate?,
  val applicationWithdrawalReason: String?,
  val bookingID: String?,
  val bookingMadeDate: LocalDate?,
  val bookingCancellationReason: String?,
  val bookingCancellationDate: LocalDate?,
  val expectedArrivalDate: LocalDate?,
  val matcherCru: String?,
  val expectedDepartureDate: LocalDate?,
  val premisesName: String?,
  val actualArrivalDate: LocalDate?,
  val actualDepartureDate: LocalDate?,
  val departureReason: String?,
  val departureMoveOnCategory: String?,
  val hasNotArrived: Boolean?,
  val notArrivedReason: String?,
  val paroleDecisionDate: LocalDate?,
  val type: String?,
)
