package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate

data class BookingsReportRow(
  val bookingId: String?,
  val referralId: String?,
  val referralDate: LocalDate?,
  val personName: String?,
  val pncNumber: String?,
  val gender: String?,
  val ethnicity: String?,
  val dateOfBirth: LocalDate?,
  val riskOfSeriousHarm: String?,
  val registeredSexOffender: String?,
  val historyOfSexualOffence: String?,
  val concerningSexualBehaviour: String?,
  val needForAccessibleProperty: Boolean?,
  val historyOfArsonOffence: String?,
  val concerningArsonBehaviour: String?,
  val dutyToReferMade: Boolean?,
  val dateDutyToReferMade: LocalDate?,
  val dutyToReferLocalAuthorityAreaName: String?,
  val isReferralEligibleForCas3: Boolean?,
  val referralEligibilityReason: String?,
  val probationRegion: String,
  val pdu: String?,
  val localAuthority: String?,
  val town: String?,
  val postCode: String?,
  val crn: String,
  val offerAccepted: Boolean,
  val isCancelled: Boolean,
  val cancellationReason: String?,
  val startDate: LocalDate?,
  val endDate: LocalDate?,
  val actualEndDate: LocalDate?,
  val currentNightsStayed: Int?,
  val actualNightsStayed: Int?,
  val accommodationOutcome: String?,
)
