package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate

data class PlacementApplicationReportRow(
  val crn: String,
  val tier: String?,
  val applicationSubmittedAt: LocalDate?,
  val applicationAssessedDate: LocalDate?,
  val assessorCru: String?,
  val assessmentDecision: String?,
  val assessmentDecisionRationale: String?,
  val placementRequestId: String,
  val placementRequestSubmittedAt: LocalDate?,
  val requestedArrivalDate: LocalDate?,
  val requestedDurationDays: Int?,
  val decision: String?,
  val decisionMadeAt: LocalDate?,
  val ageInYears: Int?,
  val gender: String?,
  val mappa: String,
  val offenceId: String?,
  val noms: String?,
  val sentenceType: String?,
  val releaseType: String?,
  val referralLdu: String?,
  val referralTeam: String?,
  val referralRegion: String?,
  val referrerUsername: String?,
  val targetLocation: String?,
  val applicationWithdrawalDate: LocalDate?,
  val applicationWithdrawalReason: String?,
  val placementRequestType: String?,
  val paroleDecisionDate: LocalDate?,
  val assessmentAppealCount: Int?,
  val lastAssessmentAppealedDecision: String?,
  val lastAssessmentAppealedDate: LocalDate?,
  val assessmentAppealedFromStatus: String?,
)
