package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate

data class PlacementApplicationReportRow(
  val id: String,
  val crn: String,
  val requestedArrivalDate: LocalDate?,
  val requestedDurationDays: Int?,
  val placementRequestSubmittedAt: LocalDate?,
  val decision: String?,
  val decisionMadeAt: LocalDate?,
  val applicationSubmittedAt: LocalDate?,
  val applicationAssessedDate: LocalDate?,
  val assessorCru: String?,
  val assessmentDecision: String?,
  val assessmentDecisionRationale: String?,
  val ageInYears: Int?,
  val gender: String?,
  val mappa: String,
  val offenceId: String?,
  val noms: String?,
  val sentenceType: String?,
  val releaseType: String?,
  val referralLdu: String?,
  val referralTeam: String?,
  val referralRegion: String?,
  val referrerUsername: String?,
  val targetLocation: String?,
  val applicationWithdrawalDate: LocalDate?,
  val applicationWithdrawalReason: String?,
  val bookingID: String?,
  val bookingCancellationReason: String?,
  val bookingCancellationDate: LocalDate?,
  val expectedArrivalDate: LocalDate?,
  val expectedDepartureDate: LocalDate?,
  val premisesName: String?,
  val actualArrivalDate: LocalDate?,
  val actualDepartureDate: LocalDate?,
  val departureReason: String?,
  val departureMoveOnCategory: String?,
  val hasNotArrived: Boolean?,
  val notArrivedReason: String?,
  val placementRequestType: String?,
  val paroleDecisionDate: LocalDate?,
)
