package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

data class ReferralsMetricsReportRow(
  val tier: String,
  val numberOfUniqueReferrals: Int,
  val referralsAccepted: Int,
  val assessmentCompletionTimeliness: String,
  val referralsWithInformationRequests: Int,
  val referralsRejectedAccommodationNeedOnly: Int,
  val referralsRejectedNeedsCannotBeMet: Int,
  val referralsRejectedSupervisionPeriodTooShort: Int,
  val referralsRejectedRiskTooLow: Int,
  val referralsRejectedOtherReasons: Int,
  val referralsRejectedRequestedInformationNotProvided: Int,
  val referralsRejectedInsufficientContingencyPlan: Int,
  val referralsRejectedInsufficientMoveOnPlan: Int,
  val referralsRejectedRiskTooHighToCommunity: Int,
  val referralsRejectedRiskTooHighToOtherPeopleInAP: Int,
  val referralsRejectedRiskToHighToStaff: Int,
  val referralsWithdrawn: Int,
  val referralsByReleaseTypeLicence: Int,
  val referralsByReleaseTypeHdc: Int,
  val referralsByReleaseTypePSS: Int,
  val referralsByReleaseTypeParole: Int,
)
