package uk.gov.justice.digital.hmpps.approvedpremisesapi.reporting.model

import java.time.LocalDate

data class TransitionalAccommodationReferralReportRow(
  val referralId: String?,
  val referralDate: LocalDate?,
  val personName: String?,
  val pncNumber: String?,
  val crn: String,
  val gender: String?,
  val ethnicity: String?,
  val dateOfBirth: LocalDate?,
  val registeredSexOffender: String?,
  val historyOfSexualOffence: String?,
  val concerningSexualBehaviour: String?,
  val needForAccessibleProperty: String?,
  val riskOfSeriousHarm: String?,
  val historyOfArsonOffence: String?,
  val concerningArsonBehaviour: String?,
  val dutyToReferMade: String?,
  val dateDutyToReferMade: LocalDate?,
  val dutyToReferLocalAuthorityAreaName: String?,
  val town: String?,
  val postCode: String?,
  val probationRegion: String,
  val pdu: String?,
  val referralSubmittedDate: LocalDate?,
  val referralRejected: String?,
  val rejectionReason: String?,
  val rejectionDate: LocalDate?,
  val sourceOfReferral: String?,
  val prisonAtReferral: String?,
  val releaseDate: LocalDate?,
  val accommodationRequiredDate: LocalDate?,
  val bookingOffered: String?,
)
