package uk.gov.justice.digital.hmpps.approvedpremisesapi.controller.cas1

import io.swagger.v3.oas.annotations.Operation
import org.slf4j.LoggerFactory
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.AllocatedFilter
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ApplicationSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.AssessmentSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.BookingSearchSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1OutOfServiceBedSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1SpaceBookingResidency
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas1SpaceBookingSummarySortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.PlacementRequestSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.RiskTierLevel
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SortDirection
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SortOrder
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.TaskSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.UserSortField

@RestController
@RequestMapping(path = ["/cas1"])
class Cas1DummyController {
  private val log = LoggerFactory.getLogger(this::class.java)

  @Operation(
    description = "This is a temporary dummy endpoint that adds models missing from autogenerated swagger documentation that are expected by the UI. " +
      "This will be removed once we move away from auto generated controllers",
  )
  @GetMapping(path = ["/dummy"])
  fun test(
    @RequestBody(required = true) request: ClassesToInclude,
  ) {
    // for linting reasons
    log.info("Generating", request.javaClass.classes)
  }
}

// These are needed because the code has been generated as
// Schema = Schema(allowableValues = ["arrived", "awaiting-arrival"]) rather than the actual enum values.
// Therefore, no enum is generated. This can change when we bring the controllers into the project and can use the enums, removing them from here
data class ClassesToInclude(
  val allocatedFilter: AllocatedFilter,
  val sortDirection: SortDirection,
  val bookingSearchSortField: BookingSearchSortField,
  val applicationSortField: ApplicationSortField,
  val cas1SpaceBookingResidency: Cas1SpaceBookingResidency,
  val cas1SpaceBookingSummarySortField: Cas1SpaceBookingSummarySortField,
  val taskSortField: TaskSortField,
  val riskTierLevel: RiskTierLevel,
  val userSortField: UserSortField,
  val cas1OutOfServiceBedSortField: Cas1OutOfServiceBedSortField,
  val placementRequestSortField: PlacementRequestSortField,
  val assessmentSortField: AssessmentSortField,
  val sortOrder: SortOrder,
)
