/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas2v2

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas2v2ApplicationStatus
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RestController
interface ReferenceDataCas2v2 {

    fun getDelegate(): ReferenceDataCas2v2Delegate = object: ReferenceDataCas2v2Delegate {}

    @Operation(
        tags = ["Reference Data",],
        summary = "Lists all application status update choices",
        operationId = "referenceDataApplicationStatusGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = Cas2v2ApplicationStatus::class)))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/reference-data/application-status"],
            produces = ["application/json"]
    )
    fun referenceDataApplicationStatusGet(): ResponseEntity<List<Cas2v2ApplicationStatus>> {
        return getDelegate().referenceDataApplicationStatusGet()
    }
}
