/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas2v2

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas2ReportName

@RestController
interface ReportsCas2v2 {

  fun getDelegate(): uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas2v2.ReportsCas2v2Delegate = object :
      uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas2v2.ReportsCas2v2Delegate {}

  @Operation(
    tags = ["Reports"],
    summary = "Returns a 'report' spreadsheet of metrics",
    operationId = "reportsReportNameGet",
    description = """""",
    responses = [
      ApiResponse(
        responseCode = "200",
        description = "successful operation",
        content = [Content(schema = Schema(implementation = org.springframework.core.io.Resource::class))],
      ),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.GET],
    value = ["/reports/{reportName}"],
    produces = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
  )
  fun reportsReportNameGet(
    @Parameter(
      description = "name of the report to download",
      required = true,
      schema = Schema(allowableValues = ["submitted-applications", "application-status-updates", "unsubmitted-applications"]),
    ) @PathVariable("reportName") reportName: Cas2ReportName,
  ): ResponseEntity<org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody> {
    return getDelegate().reportsReportNameGet(reportName)
  }
}
