#!/bin/sh

# script/clear_cache:  Clear given type of cache e.g.
#                      script/clear_cache qCodeStaffMembers
#                      Would clear the qCodeStaffMembers cache

set -e

curl --location --request DELETE "http://127.0.0.1:8080/cache/$1"

echo "Requested cache clear - check the application logs for status"
