#!/bin/sh

# script/generate_migration: Create an empty database migration, e.g.
#                            script/generate_migration all "my migration" - creates a migration that applies to all profiles
#                            script/generate_migration local+dev+test "my migration" - creates a migration that applies only to the local & dev profiles

set -e

if [ $1 == "dev+test" ]; then
    dir="dev+test"
elif [ $1 == "all" ]; then
    dir="all"
else
    echo "Unrecognised option: $1 - must be either 'all' or 'dev+test'"
    exit 1
fi

timestamp=`date "+%Y%m%d%H%M%S"`
migration_name=`echo "$2" | awk '{print tolower($0)}' | tr ' ' '_'`
filename="$(echo ${timestamp}__${migration_name}).sql"
echo "Creating migration: $filename"
touch "src/main/resources/db/migration/$dir/$filename"
