#!/bin/sh

# script/get_client_credentials_jwt: Get a client_credentials JWT from a local docker instance of HMPPS Auth

set -e

curl --location -s --request POST 'localhost:9091/auth/oauth/token?grant_type=client_credentials' \
--header 'Content-Type: application/json' \
--header 'Content-Length: 0' \
--header 'Authorization: Basic YXBwcm92ZWQtcHJlbWlzZXMtYXBpOmNsaWVudHNlY3JldA==' \
