#!/bin/bash

if [ -z "$1" ] || ! [[ "$1" =~ ^(dev|test|preprod|prod)$ ]] || [ -z "$2" ]; then
  echo "Usage:"
  echo "pod_upload_file dev|test|preprod|prod file_path"
  exit 1
fi

environment=$1
file=$2

namespace="hmpps-community-accommodation-$environment"

pod=$(kubectl -n "$namespace" get pods -l app=hmpps-approved-premises-api -o jsonpath='{.items[0].metadata.name}')

base_name=$(basename "${file}")
target_path="/tmp/seed/$base_name"
kubectl cp "$file" "$pod:$target_path" -n "$namespace"

echo "File uploaded to $target_path on pod $pod"
