#!/bin/sh

if [ -z "$1" ]; then
  echo "You must specify an environment"
  exit 1
else
  environment=$1
fi

namespace="hmpps-community-accommodation-$environment"

pod=$(kubectl -n "$namespace" get pods -l app=hmpps-approved-premises-api -o jsonpath='{.items[0].metadata.name}')

script="""
cd ~
curl -L https://github.com/Teradata/jaqy/releases/download/v1.2.0/jaqy-1.2.0.jar --output jaqy-1.2.0.jar

jaqyChecksumResult=\$(sha256sum --check /app/jaqy-1.2.0.jar.checksum.sha256)
if [ \$? -ne 0 ]; then
  echo \"* jaqy checksum failed: \$jaqyChecksumResult *\"
  echo \"* PLEASE INVESTIGATE *\"
  exit 1
fi

curl -L https://jdbc.postgresql.org/download/postgresql-42.7.3.jar --output postgresql-42.7.3.jar

java -jar jaqy-1.2.0.jar -- \
  .classpath postgresql postgresql-42.7.3.jar \; \
  .open -u \${SPRING_DATASOURCE_USERNAME} -p \${SPRING_DATASOURCE_PASSWORD} postgresql://\${DB_HOST}/\${DB_NAME} \; \
  \"SET default_transaction_read_only = TRUE;\"
"""

kubectl -n "$namespace" exec -it "$pod" -- sh -c "$script"
