#!/bin/sh

if [ -z "$1" ]; then
  echo "You must specify an environment"
  exit 1
else
  environment=$1
fi

namespace="hmpps-community-accommodation-$environment"

pod=$(kubectl -n "$namespace" get pods -l app=hmpps-approved-premises-api -o jsonpath='{.items[0].metadata.name}')

kubectl -n "$namespace" exec -it "$pod" -- sh
