#!/bin/bash

# script/run_migration_job: Run a migration job for given type.  e.g.
#                           script/run_migration_job update_all_users_from_community_api

set -e

cd "$(dirname "$0")"
script_dir="$(pwd)"
. "$script_dir"/invoke_admin_command

invoke_admin_command "uk.gov.justice.digital.hmpps.approvedpremisesapi.cmd.RunMigrationJobCommand $1"

echo "Requested job - check the application logs for processing status"
