#!/bin/bash

# script/run_seed_job: Run a seed job for given type and name of CSV file in seed directory.  e.g.
#                      script/run_seed_job approved_premises ap_upload
#                      Would start a seed job for the hmpps-approved-premises-api/seed/ap_upload.csv file

set -e

cd "$(dirname "$0")"
script_dir="$(pwd)"
. "$script_dir"/invoke_admin_command

invoke_admin_command uk.gov.justice.digital.hmpps.approvedpremisesapi.cmd.RunSeedJobCommand "$1" "$2"

echo "Requested job - check the application logs for processing status"
