#!/bin/sh

# script/run_seed_job: Run a seed job for given type and name of CSV file in seed directory.  e.g.
#                      script/run_seed_job approved_premises ap_upload
#                      Would start a seed job for the hmpps-approved-premises-api/seed/ap_upload.csv file

set -e

curl --location --request POST 'http://127.0.0.1:8080/seed' \
--header 'Content-Type: application/json' \
--data-raw '{
    "seedType": "'$1'",
    "fileName": "'$2'"
}'

echo "Requested job - check the application logs for processing status"
