#!/bin/bash

set -e

SEED_JOB_ID=$1
DIRECTORY_NAME=$2

if [ -z "$SEED_JOB_ID" ] || [ -z "$DIRECTORY_NAME" ]
then
  echo "Usage: run_seed_from_excel_directory_job seed_job_id directory_name"
  exit 1
fi

cd "$(dirname "$0")"
script_dir="$(pwd)"
. "$script_dir"/invoke_admin_command

invoke_admin_command "uk.gov.justice.digital.hmpps.approvedpremisesapi.cmd.RunSeedFromExcelDirectoryJobCommand $1 $2"

echo "Requested job - check the application logs for processing status"
