#!/bin/bash

# script/run_seed_job_from_excel: Run a seed job for given type and name of XLSX file in seed directory.  e.g.
#                      script/run_seed_job_from_excel approved_premises ap_upload
#                      Would start a seed job for the hmpps-approved-premises-api/seed/ap_upload.xlsx file

set -e

SEED_JOB_ID=$1
FILE_NAME=$2

if [ -z "$SEED_JOB_ID" ] || [ -z "$FILE_NAME" ]
then
  echo "Usage: run_seed_from_excel_job seed_job_id file_name"
  exit 1
fi

cd "$(dirname "$0")"
script_dir="$(pwd)"
. "$script_dir"/invoke_admin_command

invoke_admin_command uk.gov.justice.digital.hmpps.approvedpremisesapi.cmd.RunSeedFromExcelJobCommand "$1" "$2"

echo "Requested job - check the application logs for processing status"

