#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

./script/development_database

echo "==> Starting server..."
./gradlew bootRunLocal
