#!/bin/sh

# script/test: Run the test suite for the application.

set -e

cd "$(dirname "$0")/.."

echo "==> Running ktlint..."
./gradlew ktlintCheck

echo "==> Running static code analyser..."
./gradlew detekt

./script/test_database

echo "==> Running tests..."
./gradlew test
