#!/bin/sh

# script/database: Launch the integration test development database

set -e

cd "$(dirname "$0")/.."

script/utils/launch-docker.sh

echo "==> Starting integration test database..."
docker-compose -f docker-compose.test.yml up -d
