/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas3

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ValidationError

@RestController
interface ApplicationsCas3 {

  fun getDelegate(): ApplicationsCas3Delegate = object : ApplicationsCas3Delegate {}

  @Operation(
    tags = ["Operations on application"],
    summary = "Soft delete a draft application",
    operationId = "deleteApplication",
    description = """""",
    responses = [
      ApiResponse(responseCode = "200", description = "successful operation"),
      ApiResponse(
        responseCode = "400",
        description = "invalid params",
        content = [Content(schema = Schema(implementation = ValidationError::class))],
      ),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.DELETE],
    value = ["/applications/{applicationId}"],
    produces = ["application/problem+json"],
  )
  fun deleteApplication(
    @Parameter(
      description = "Id of the application",
      required = true,
    ) @PathVariable("applicationId") applicationId: java.util.UUID,
  ): ResponseEntity<Unit> {
    return getDelegate().deleteApplication(applicationId)
  }
}
