/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas3

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas3BedspaceSearchParameters
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas3BedspaceSearchResults
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ValidationError
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*

@RestController
interface BedspacesCas3 {

    fun getDelegate(): BedspacesCas3Delegate = object: BedspacesCas3Delegate {}

    @Operation(
        tags = ["default",],
        summary = "Searches for available Beds within the given parameters",
        operationId = "postBedspaceSearch",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Cas3BedspaceSearchResults::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/bedspaces/search"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun postBedspaceSearch(@Parameter(description = "", required = true) @RequestBody cas3BedspaceSearchParameters: Cas3BedspaceSearchParameters): ResponseEntity<Cas3BedspaceSearchResults> {
        return getDelegate().postBedspaceSearch(cas3BedspaceSearchParameters)
    }
}
