/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api.cas3

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Cas3ReportType
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RestController
interface ReportsCas3 {

    fun getDelegate(): ReportsCas3Delegate = object: ReportsCas3Delegate {}

    @Operation(
        tags = ["CAS3 Reports",],
        summary = "Returns a spreadsheet of all data metrics for the 'reportName'.",
        operationId = "reportsReportNameGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Successfully retrieved the report", content = [Content(schema = Schema(implementation = org.springframework.core.io.Resource::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/reports/{reportName}"],
            produces = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
    )
    fun reportsReportNameGet(@Parameter(description = "Name of the report to download", required = true, schema = Schema(allowableValues = ["referral", "booking", "bedUsage", "bedOccupancy", "futureBookings", "futureBookingsCsv", "bookingGap"])) @PathVariable("reportName") reportName: Cas3ReportType,@Parameter(description = "Start of date range to return", required = true) @RequestParam(value = "startDate", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) startDate: java.time.LocalDate,@Parameter(description = "End of date range to return", required = true) @RequestParam(value = "endDate", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) endDate: java.time.LocalDate,@Parameter(description = "If provided, only this region will be returned") @RequestParam(value = "probationRegionId", required = false) probationRegionId: java.util.UUID?): ResponseEntity<org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody> {
        return getDelegate().reportsReportNameGet(reportName, startDate, endDate, probationRegionId)
    }
}
