TRUNCATE TABLE premises CASCADE;

TRUNCATE TABLE applications CASCADE;
TRUNCATE TABLE assessments CASCADE;

TRUNCATE TABLE cas_2_applications CASCADE;

DELETE FROM domain_events WHERE domain_events.type in (
   'CAS2_APPLICATION_STATUS_UPDATED', 'CAS2_APPLICATION_SUBMITTED'
);