/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Appeal
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Application
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ApplicationSummary
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ApplicationTimelineNote
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Document
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.NewAppeal
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.NewApplication
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.NewApplicationTimelineNote
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.NewWithdrawal
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Problem
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.RequestForPlacement
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ServiceName
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SubmitApplication
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.UpdateApplication
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ValidationError
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Withdrawables
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RestController
interface ApplicationsApi {

    fun getDelegate(): ApplicationsApiDelegate = object: ApplicationsApiDelegate {}

    @Operation(
        tags = ["Application data",],
        summary = "Get an appeal on an application",
        operationId = "applicationsApplicationIdAppealsAppealIdGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Appeal::class))]),
            ApiResponse(responseCode = "404", description = "invalid applicationId or appealId", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications/{applicationId}/appeals/{appealId}"],
            produces = ["application/json"]
    )
    fun applicationsApplicationIdAppealsAppealIdGet(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "ID of the appeal", required = true) @PathVariable("appealId") appealId: java.util.UUID): ResponseEntity<Appeal> {
        return getDelegate().applicationsApplicationIdAppealsAppealIdGet(applicationId, appealId)
    }

    @Operation(
        tags = ["Application data",],
        summary = "Add an appeal to an application",
        operationId = "applicationsApplicationIdAppealsPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "successful operation", content = [Content(schema = Schema(implementation = Appeal::class))]),
            ApiResponse(responseCode = "404", description = "invalid applicationId", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/applications/{applicationId}/appeals"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun applicationsApplicationIdAppealsPost(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "the appeal to add", required = true) @RequestBody body: NewAppeal): ResponseEntity<Appeal> {
        return getDelegate().applicationsApplicationIdAppealsPost(applicationId, body)
    }

    @Operation(
        tags = ["Application data",],
        summary = "Returns meta info on documents at the person level or at the Conviction level for the index Offence of this application.",
        operationId = "applicationsApplicationIdDocumentsGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = Document::class)))]),
            ApiResponse(responseCode = "404", description = "invalid CRN", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications/{applicationId}/documents"],
            produces = ["application/json"]
    )
    fun applicationsApplicationIdDocumentsGet(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID): ResponseEntity<List<Document>> {
        return getDelegate().applicationsApplicationIdDocumentsGet(applicationId)
    }

    @Operation(
        tags = ["Operations on applications",],
        summary = "Gets a single application by its ID",
        operationId = "applicationsApplicationIdGet",
        description = """deprecated for cas3, use /cas3/applications/{applicationId}""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Application::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications/{applicationId}"],
            produces = ["application/json"]
    )
    fun applicationsApplicationIdGet(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID): ResponseEntity<Application> {
        return getDelegate().applicationsApplicationIdGet(applicationId)
    }

    @Operation(
        tags = ["Add a note on applications",],
        summary = "Add a note on applications",
        operationId = "applicationsApplicationIdNotesPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = ApplicationTimelineNote::class))]),
            ApiResponse(responseCode = "404", description = "invalid applicationId", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/applications/{applicationId}/notes"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun applicationsApplicationIdNotesPost(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "the note to add", required = true) @RequestBody body: NewApplicationTimelineNote): ResponseEntity<ApplicationTimelineNote> {
        return getDelegate().applicationsApplicationIdNotesPost(applicationId, body)
    }

    @Operation(
        tags = ["Operations on applications",],
        summary = "Updates an application",
        operationId = "applicationsApplicationIdPut",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Application::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.PUT],
            value = ["/applications/{applicationId}"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun applicationsApplicationIdPut(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "Information to update the application with", required = true) @RequestBody body: UpdateApplication): ResponseEntity<Application> {
        return getDelegate().applicationsApplicationIdPut(applicationId, body)
    }

    @Operation(
        tags = ["default",],
        summary = "Returns a list of Requests for Placement for the given application.",
        operationId = "applicationsApplicationIdRequestsForPlacementGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = RequestForPlacement::class)))]),
            ApiResponse(responseCode = "404", description = "invalid CRN", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications/{applicationId}/requests-for-placement"],
            produces = ["application/json"]
    )
    fun applicationsApplicationIdRequestsForPlacementGet(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID): ResponseEntity<List<RequestForPlacement>> {
        return getDelegate().applicationsApplicationIdRequestsForPlacementGet(applicationId)
    }

    @Operation(
        tags = ["Application data",],
        summary = "Submits an Application",
        operationId = "applicationsApplicationIdSubmissionPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successfully submitted the application"),
            ApiResponse(responseCode = "400", description = "application has already been submitted", content = [Content(schema = Schema(implementation = ValidationError::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/applications/{applicationId}/submission"],
            produces = ["application/problem+json"],
            consumes = ["application/json"]
    )
    fun applicationsApplicationIdSubmissionPost(@Parameter(description = "Id of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "Information needed to submit an application", required = true) @RequestBody submitApplication: SubmitApplication): ResponseEntity<Unit> {
        return getDelegate().applicationsApplicationIdSubmissionPost(applicationId, submitApplication)
    }

    @Operation(
        tags = ["Operations on applications",],
        summary = "Returns a list of withdrawable items associated with this application, including the application itself, if withdrawable",
        operationId = "applicationsApplicationIdWithdrawablesWithNotesGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(schema = Schema(implementation = Withdrawables::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications/{applicationId}/withdrawablesWithNotes"],
            produces = ["application/json"]
    )
    fun applicationsApplicationIdWithdrawablesWithNotesGet(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "If given, only users for this service will be returned", `in` = ParameterIn.HEADER, required = true, schema = Schema(allowableValues = ["approved-premises", "cas2", "cas2v2", "temporary-accommodation"])) @RequestHeader(value = "X-Service-Name", required = true) xServiceName: ServiceName): ResponseEntity<Withdrawables> {
        return getDelegate().applicationsApplicationIdWithdrawablesWithNotesGet(applicationId, xServiceName)
    }

    @Operation(
        tags = ["Operations on applications",],
        summary = "Withdraws an application with a reason",
        operationId = "applicationsApplicationIdWithdrawalPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation"),
            ApiResponse(responseCode = "404", description = "invalid applicationId", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/applications/{applicationId}/withdrawal"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun applicationsApplicationIdWithdrawalPost(@Parameter(description = "ID of the application", required = true) @PathVariable("applicationId") applicationId: java.util.UUID,@Parameter(description = "details of the withdrawal", required = true) @RequestBody body: NewWithdrawal): ResponseEntity<Unit> {
        return getDelegate().applicationsApplicationIdWithdrawalPost(applicationId, body)
    }

    @Operation(
        tags = ["Operations on all applications",],
        summary = "Lists all applications that the user has created",
        operationId = "applicationsGet",
        description = """deprecated, for cas1 use /cas1/applications and for cas3 use /cas3/applications""",
        responses = [
            ApiResponse(responseCode = "200", description = "successful operation", content = [Content(array = ArraySchema(schema = Schema(implementation = ApplicationSummary::class)))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/applications"],
            produces = ["application/json"]
    )
    fun applicationsGet(@Parameter(description = "Which service to get applications for, defaults to approved-premises", `in` = ParameterIn.HEADER, schema = Schema(allowableValues = ["approved-premises", "cas2", "cas2v2", "temporary-accommodation"])) @RequestHeader(value = "X-Service-Name", required = false) xServiceName: ServiceName?): ResponseEntity<List<ApplicationSummary>> {
        return getDelegate().applicationsGet(xServiceName)
    }

    @Operation(
        tags = ["Operations on applications",],
        summary = "Creates an application",
        operationId = "applicationsPost",
        description = """deprecated for cas3, use /cas3/applications""",
        responses = [
            ApiResponse(responseCode = "201", description = "successful operation", content = [Content(schema = Schema(implementation = Application::class))]),
            ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
            ApiResponse(responseCode = "404", description = "invalid CRN", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/applications"],
            produces = ["application/json", "application/problem+json"],
            consumes = ["application/json"]
    )
    fun applicationsPost(@Parameter(description = "Information to create a blank application with", required = true) @RequestBody body: NewApplication,@Parameter(description = "Which service the application will belong to, defaults to approved-premises", `in` = ParameterIn.HEADER, schema = Schema(allowableValues = ["approved-premises", "cas2", "cas2v2", "temporary-accommodation"])) @RequestHeader(value = "X-Service-Name", required = false) xServiceName: ServiceName?, @RequestParam(value = "createWithRisks", required = false) createWithRisks: kotlin.Boolean?): ResponseEntity<Application> {
        return getDelegate().applicationsPost(body, xServiceName, createWithRisks)
    }
}
