/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api

import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Problem
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SeedFromExcelRequest
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*

@RestController
interface SeedFromExcelApi {

    fun getDelegate(): SeedFromExcelApiDelegate = object: SeedFromExcelApiDelegate {}

    @Operation(
        tags = ["default",],
        summary = "Starts the data seeding from Excel process, can only be called from a local connection",
        operationId = "seedFromExcelPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "202", description = "successfully requested task"),
            ApiResponse(responseCode = "401", description = "not authenticated", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "403", description = "unauthorised", content = [Content(schema = Schema(implementation = Problem::class))]),
            ApiResponse(responseCode = "500", description = "unexpected error", content = [Content(schema = Schema(implementation = Problem::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/seedFromExcel"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun seedFromExcelPost(@Parameter(description = "", required = true) @RequestBody seedFromExcelRequest: SeedFromExcelRequest): ResponseEntity<Unit> {
        return getDelegate().seedFromExcelPost(seedFromExcelRequest)
    }
}
