/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package uk.gov.justice.digital.hmpps.approvedpremisesapi.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.AllocatedFilter
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.NewReallocation
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Reallocation
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ServiceName
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.SortDirection
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.Task
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.TaskSortField
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.TaskType
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.TaskWrapper
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.UserQualification
import uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ValidationError
import kotlin.collections.List

@RestController
interface TasksApi {

  fun getDelegate(): TasksApiDelegate = object : TasksApiDelegate {}

  @Operation(
    tags = ["Task data"],
    summary = "List all tasks",
    operationId = "tasksGet",
    description = """""",
    responses = [
      ApiResponse(responseCode = "200", description = "successfully retrieved tasks", content = [Content(array = ArraySchema(schema = Schema(implementation = Task::class)))]),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.GET],
    value = ["/tasks"],
    produces = ["application/json"],
  )
  fun tasksGet(@RequestParam(value = "type", required = false) type: TaskType?, @RequestParam(value = "types", required = false) types: kotlin.collections.List<TaskType>?, @RequestParam(value = "page", required = false) page: kotlin.Int?, @RequestParam(value = "perPage", required = false) perPage: kotlin.Int?, @RequestParam(value = "sortBy", required = false) sortBy: TaskSortField?, @RequestParam(value = "sortDirection", required = false) sortDirection: SortDirection?, @RequestParam(value = "allocatedFilter", required = false) allocatedFilter: AllocatedFilter?, @RequestParam(value = "apAreaId", required = false) apAreaId: java.util.UUID?, @RequestParam(value = "cruManagementAreaId", required = false) cruManagementAreaId: java.util.UUID?, @RequestParam(value = "allocatedToUserId", required = false) allocatedToUserId: java.util.UUID?, @RequestParam(value = "requiredQualification", required = false) requiredQualification: UserQualification?, @RequestParam(value = "crnOrName", required = false) crnOrName: kotlin.String?, @RequestParam(value = "isCompleted", required = false) isCompleted: kotlin.Boolean?): ResponseEntity<List<Task>> = getDelegate().tasksGet(type, types, page, perPage, sortBy, sortDirection, allocatedFilter, apAreaId, cruManagementAreaId, allocatedToUserId, requiredQualification, crnOrName, isCompleted)

  @Operation(
    tags = ["Operations on applications"],
    summary = "Unallocates a task for an application",
    operationId = "tasksTaskTypeIdAllocationsDelete",
    description = """""",
    responses = [
      ApiResponse(responseCode = "200", description = "successful operation"),
      ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.DELETE],
    value = ["/tasks/{taskType}/{id}/allocations"],
    produces = ["application/problem+json"],
  )
  fun tasksTaskTypeIdAllocationsDelete(@Parameter(description = "ID of the task", required = true) @PathVariable("id") id: java.util.UUID, @Parameter(description = "Task type", required = true) @PathVariable("taskType") taskType: kotlin.String): ResponseEntity<Unit> = getDelegate().tasksTaskTypeIdAllocationsDelete(id, taskType)

  @Operation(
    tags = ["Operations on applications"],
    summary = "Reallocates a task for an application",
    operationId = "tasksTaskTypeIdAllocationsPost",
    description = """""",
    responses = [
      ApiResponse(responseCode = "201", description = "successful operation", content = [Content(schema = Schema(implementation = Reallocation::class))]),
      ApiResponse(responseCode = "400", description = "invalid params", content = [Content(schema = Schema(implementation = ValidationError::class))]),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.POST],
    value = ["/tasks/{taskType}/{id}/allocations"],
    produces = ["application/json", "application/problem+json"],
    consumes = ["application/json"],
  )
  fun tasksTaskTypeIdAllocationsPost(@Parameter(description = "ID of the task", required = true) @PathVariable("id") id: java.util.UUID, @Parameter(description = "Task type", required = true) @PathVariable("taskType") taskType: kotlin.String, @Parameter(description = "Only assessments for this service will be returned", `in` = ParameterIn.HEADER, required = true, schema = Schema(allowableValues = ["approved-premises", "cas2", "cas2v2", "temporary-accommodation"])) @RequestHeader(value = "X-Service-Name", required = true) xServiceName: ServiceName, @Parameter(description = "") @RequestBody(required = false) body: NewReallocation?): ResponseEntity<Reallocation> = getDelegate().tasksTaskTypeIdAllocationsPost(id, taskType, xServiceName, body)

  @Operation(
    tags = ["Application data"],
    summary = "Gets a task for an application",
    operationId = "tasksTaskTypeIdGet",
    description = """""",
    responses = [
      ApiResponse(responseCode = "200", description = "successfully retrieved task", content = [Content(schema = Schema(implementation = TaskWrapper::class))]),
    ],
  )
  @RequestMapping(
    method = [RequestMethod.GET],
    value = ["/tasks/{taskType}/{id}"],
    produces = ["application/json"],
  )
  fun tasksTaskTypeIdGet(@Parameter(description = "ID of the task", required = true) @PathVariable("id") id: java.util.UUID, @Parameter(description = "Task type", required = true) @PathVariable("taskType") taskType: kotlin.String): ResponseEntity<TaskWrapper> = getDelegate().tasksTaskTypeIdGet(id, taskType)
}
