name: Deploy to test

on:
  workflow_dispatch:

jobs:
  docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@95c48db64a6d50acd1f8f8a0f93d1019727e5b4d
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      push: true
      docker_multiplatform: false
      tag_latest: false

  deploy_test:
    name: Deploy to the test environment
    needs:
      - docker_build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@95c48db64a6d50acd1f8f8a0f93d1019727e5b4d
    secrets: inherit
    with:
      environment: 'test'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
      show_changelog: false
