name: E2E tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cas1_e2e_test:
    name: "CAS1 E2E"
    uses: ministryofjustice/hmpps-approved-premises-ui/.github/workflows/e2e_tests.yml@3fcc8ffbda99b77a24ed2d3416ac285aef6e5e9f # main 2026-04-02
    secrets: inherit

  cas2_e2e_test:
    name: "CAS2 E2E"
    uses: ministryofjustice/hmpps-community-accommodation-tier-2-ui/.github/workflows/e2e_tests.yml@77cc6ec1dd5ed994309df8960421cbd3ba1ad5aa # main 2026-04-02
    secrets: inherit

  cas2_bail_e2e_test:
    name: "CAS2 Bail E2E"
    uses: ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/.github/workflows/e2e_tests.yml@c28d809de3db8bcee97d93a72d4eed9d060e92e3 # main 2026-04-02
    secrets: inherit

  cas3_e2e_test:
    name: "CAS3 E2E"
    uses: ministryofjustice/hmpps-temporary-accommodation-ui/.github/workflows/e2e_tests.yml@ed0da3d66fc552dfdd1beaaf22cfc21c296162a4 # main 2026-04-02
    secrets: inherit
