name: E2E tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cas1_e2e_test:
    name: "CAS1 E2E"
    uses: ministryofjustice/hmpps-approved-premises-ui/.github/workflows/e2e_tests.yml@main
    secrets: inherit

  cas2_e2e_test:
    name: "CAS2 E2E"
    uses: ministryofjustice/hmpps-community-accommodation-tier-2-ui/.github/workflows/e2e_tests.yml@main
    secrets: inherit

  cas2_bail_e2e_test:
    name: "CAS2 Bail E2E"
    uses: ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/.github/workflows/e2e_tests.yml@main
    secrets: inherit

  cas3_e2e_test:
    name: "CAS3 E2E"
    uses: ministryofjustice/hmpps-temporary-accommodation-ui/.github/workflows/e2e_tests.yml@main
    secrets: inherit
