name: Generate CAS1 UI Types

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Trigger CAS1 UI Type Generation Workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'hmpps-approved-premises-ui',
              workflow_id: 'generate-types.yml',
              ref: 'main'
            })
