name: Generate CAS1 UI Types

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Trigger CAS1 UI Type Generation Workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'hmpps-approved-premises-ui',
              workflow_id: 'generate-types.yml',
              ref: 'main'
            })
