name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - 'main'
#      - 'chore/CAS-2002-delete-merge-migration-job-and-unused-columns'

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      push: true
      docker_multiplatform: false

  deploy_dev:
    name: Deploy to the development environment
    needs:
      - test
      - docker_build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'development'
      app_version: '${{ needs.docker_build.outputs.app_version }}'

  e2e:
    name: E2E tests
    needs:
      - deploy_dev
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  cas1_generate_types:
    needs: e2e
    name: Run the generate types job for the CAS1 UI
    uses: ./.github/workflows/generate-cas1-ui-types.yml
    secrets: inherit

  cas2_generate_types:
    needs: e2e
    name: Run the generate types job for the CAS2 UI
    uses: ./.github/workflows/generate-cas2-ui-types.yml
    secrets: inherit

  cas2v2_generate_types:
    needs: e2e
    name: Run the generate types job for the CAS2v2 UI
    uses: ./.github/workflows/generate-cas2v2-ui-types.yml
    secrets: inherit

  cas3_generate_types:
    needs: e2e
    name: Run the generate types job for the CAS3 UI
    uses: ./.github/workflows/generate-cas3-ui-types.yml
    secrets: inherit

  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - docker_build
      - e2e
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
      slack_notification: 'true'

  deploy_prod:
    name: Deploy to production environment
    needs:
      - docker_build
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
      slack_notification: 'true'
