name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ""
      push: ${{ inputs.push || true }}
      docker_multiplatform: false
      additional_docker_build_args: ""
