name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - 'main'
      - 'feature/FM-496-upgrade-to-spring-boot-4'

jobs:
  verify:
    permissions:
      contents: read
    name: Test
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  docker_build:
    permissions:
      contents: read
      packages: write
    name: Build docker image
    uses: ./.github/workflows/docker_build.yml
    secrets: inherit

  deploy_dev:
    permissions:
      contents: read
      packages: write
    name: Deploy to the development environment
    needs:
      - verify
      - docker_build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'development'
      app_version: '${{ needs.docker_build.outputs.app_version }}'

  e2e:
    permissions:
      contents: read
    name: E2E tests
    needs:
      - deploy_dev
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  ui_generate_types:
    permissions:
      contents: read
      pull-requests: write
    needs: e2e
    name: Run the generate types job for all the CAS UIs
    uses: ./.github/workflows/generate-ui-types.yml
    secrets: inherit

  deploy_preprod:
    permissions:
      contents: read
      packages: write
    name: Deploy to pre-production environment
    needs:
      - docker_build
      - e2e
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
      slack_notification: 'true'

  deploy_prod:
    permissions:
      contents: read
      packages: write
    name: Deploy to production environment
    needs:
      - docker_build
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: 'prod'
      app_version: '${{ needs.docker_build.outputs.app_version }}'
      slack_notification: 'true'
