name: Pull Request Verify

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  verify:
    permissions:
      contents: read
    name: Test
    uses: ./.github/workflows/verify.yml
    secrets: inherit